apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-site-deploy
  namespace: test
  labels:
    app: simple-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-site
  template:
    metadata:
      labels:
        app: simple-site
    spec:
      containers:
      - name: web
        image: geoffreysamper/simple-site:3.0
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: simple-site-svc
  namespace: test
  labels:
    app: simple-site
  annotations:
spec:
  selector:
      app: simple-site
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/subnets: subnet-a4f0098e,subnet-457ed533,subnet-95c904cd
  labels:    
  name: simple-site-ingress
spec:
  rules:
  - host: www.simple-site.be
    http:
      paths:
      - backend:
          serviceName: simple-site-svc
          servicePort: 5000
        path: /
