apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-site-deploy
  namespace: test
  labels:
    app: simple-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-site
  template:
    metadata:
      labels:
        app: simple-site
    spec:
      containers:
      - name: web
        image: geoffreysamper/simple-site:15.0
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: simple-site-svc
  namespace: test
  labels:
    app: simple-site
  annotations:
spec:
  type: NodePort
  selector:
      app: simple-site
  ports:
    - name: http
      port: 80
      targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-site-ingress
  namespace: "test"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    
  labels:
    app: simple-site-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: simple-site-svc
              servicePort: 80
